function stateList() {
var data = [];
data.push( ["The United States", 99 ]);
data.push( ["Alabama", 1 ]);
data.push( ["Alaska", 2 ]);
data.push( ["Arizona", 4 ]);
data.push( ["Arkansas", 5 ]);
data.push( ["California", 6 ]);
data.push( ["Colorado", 8 ]);
data.push( ["Connecticut", 9 ]);
data.push( ["Delaware", 10 ]);
data.push( ["Florida", 12 ]);
data.push( ["Georgia", 13 ]);
data.push( ["Hawaii", 15 ]);
data.push( ["Idaho", 16 ]);
data.push( ["Illinois", 17 ]);
data.push( ["Indiana", 18 ]);
data.push( ["Iowa", 19 ]);
data.push( ["Kansas", 20 ]);
data.push( ["Kentucky", 21 ]);
data.push( ["Louisiana", 22 ]);
data.push( ["Maine", 23 ]);
data.push( ["Maryland", 24 ]);
data.push( ["Massachusetts", 25 ]);
data.push( ["Michigan", 26 ]);
data.push( ["Minnesota", 27 ]);
data.push( ["Mississippi", 28 ]);
data.push( ["Missouri", 29 ]);
data.push( ["Montana", 30 ]);
data.push( ["Nebraska", 31 ]);
data.push( ["Nevada", 32 ]);
data.push( ["New Hampshire", 33 ]);
data.push( ["New Mexico", 35 ]);
data.push( ["New York", 36 ]);
data.push( ["North Carolina", 37 ]);
data.push( ["North Dakota", 38 ]);
data.push( ["Ohio", 39 ]);
data.push( ["Oklahoma", 40 ]);
data.push( ["Oregon", 41 ]);
data.push( ["Pennsylvania", 42 ]);
data.push( ["South Carolina", 45 ]);
data.push( ["South Dakota", 46 ]);
data.push( ["Tennessee", 47 ]);
data.push( ["Texas", 48 ]);
data.push( ["Utah", 49 ]);
data.push( ["Vermont", 50 ]);
data.push( ["Virginia", 51 ]);
data.push( ["Washington", 53 ]);
data.push( ["West Virginia", 54 ]);
data.push( ["Wisconsin", 55 ]);
data.push( ["Wyoming", 56 ]);
return data;
};
